import fs from "fs-extra";
import path from "path";
import chalk from "chalk";

export async function addCommand(packageName: string): Promise<void> {
  if (!packageName) {
    console.log(chalk.red("❌ Package name is required."));
    console.log(chalk.yellow("Usage: ai add <package>"));
    process.exit(1);
  }

  const projectRoot = process.cwd();
  const packagesDir = path.join(projectRoot, "packages");

  try {
    await fs.ensureDir(packagesDir);

    const packageDir = path.join(packagesDir, packageName);

    if (await fs.pathExists(packageDir)) {
      console.log(chalk.yellow(`⚠️ Package "${packageName}" already exists.`));
      return;
    }

    await fs.ensureDir(packageDir);

    await fs.writeFile(
      path.join(packageDir, "README.md"),
      `# ${packageName}

Generated by AI Business OS CLI.
`
    );

    await fs.writeJson(
      path.join(packageDir, "package.json"),
      {
        name: packageName,
        version: "1.0.0",
        private: true
      },
      { spaces: 2 }
    );

    console.log(chalk.green("✅ Package created successfully."));
    console.log(chalk.gray(`📦 ${packageDir}`));
  } catch (error) {
    console.error(chalk.red("❌ Failed to create package."));
    console.error(error);
    process.exit(1);
  }
}