import fs from "fs-extra";
import path from "path";
import chalk from "chalk";

export async function initCommand(projectName?: string): Promise<void> {
  const name = projectName || "ai-business-os-project";
  const projectPath = path.resolve(process.cwd(), name);

  console.log(chalk.cyan("\n🚀 AI Business OS"));
  console.log(chalk.gray("--------------------------------"));

  if (await fs.pathExists(projectPath)) {
    console.log(chalk.red(`❌ Directory already exists: ${projectPath}`));
    process.exit(1);
  }

  try {
    await fs.ensureDir(projectPath);

    await fs.ensureDir(path.join(projectPath, "agents"));
    await fs.ensureDir(path.join(projectPath, "skills"));
    await fs.ensureDir(path.join(projectPath, "prompts"));
    await fs.ensureDir(path.join(projectPath, "templates"));
    await fs.ensureDir(path.join(projectPath, "workflows"));

    await fs.writeFile(
      path.join(projectPath, "README.md"),
      `# ${name}

Generated by AI Business OS CLI.
`
    );

    await fs.writeJson(
      path.join(projectPath, "ai-business-os.json"),
      {
        name,
        version: "1.1.0",
        createdAt: new Date().toISOString()
      },
      { spaces: 2 }
    );

    console.log(chalk.green("✅ Project initialized successfully."));
    console.log(chalk.gray(`📁 ${projectPath}`));

    console.log("\nNext steps:");
    console.log(chalk.yellow(`  cd ${name}`));
    console.log(chalk.yellow("  ai doctor"));
    console.log(chalk.yellow("  ai install backend-engineer"));
  } catch (error) {
    console.error(chalk.red("❌ Failed to initialize project."));
    console.error(error);
    process.exit(1);
  }
}