export interface FeatureItem {
  title: string;
  description: string;
}

export interface TestimonialItem {
  quote: string;
  author: string;
  role: string;
}

export interface PricingPlan {
  name: string;
  price: string;
  period: string;
  features: string[];
  highlighted: boolean;
}

export interface FaqItem {
  question: string;
  answer: string;
}

export interface ServiceItem {
  title: string;
  description: string;
}

export interface ProductItem {
  name: string;
  description: string;
  price: string;
}

export interface BlogPost {
  title: string;
  excerpt: string;
}

export interface ValueItem {
  title: string;
  description: string;
}

export interface SiteContent {
  home: {
    kicker: string;
    headline: string;
    subheadline: string;
    ctaLabel: string;
    features: FeatureItem[];
    testimonials: TestimonialItem[];
    ctaTitle: string;
    ctaSubtitle: string;
    newsletterTitle: string;
    newsletterSubtitle: string;
  };
  about: { title: string; intro: string; body: string; values: ValueItem[] };
  services: { title: string; intro: string; items: ServiceItem[] };
  products: { title: string; intro: string; items: ProductItem[] };
  pricing: { title: string; intro: string; plans: PricingPlan[] };
  faq: { title: string; intro: string; items: FaqItem[] };
  blog: { title: string; intro: string; posts: BlogPost[] };
  contact: { title: string; intro: string; email: string };
  privacy: { title: string; body: string[] };
  terms: { title: string; body: string[] };
  notFound: { title: string; message: string };
  seo: { title: string; description: string };
}

/** Generated by the AI Business OS Website Builder Content Engine (Provider Layer). */
export const content: SiteContent = {{contentJson}};
