import type { CollectionStore } from "@/lib/db/collectionStore";
import { recordAuditEvent } from "@/lib/audit/log";
import { createRepository, deleteRepository, isGitHubConfigured } from "@/lib/github/client";
import { commitAll, ensureRepoInitialized, pushToRemote } from "@/lib/git/client";
import {
  createDeployment,
  createProject,
  deleteProject,
  isVercelConfigured,
  linkGitRepository,
} from "@/lib/vercel/client";
import { updateWebsiteDeployment } from "@/lib/websites/registry";
import type { DeploymentPipelineInput, DeploymentPipelineResult, DeploymentStepLog } from "./types";

/**
 * AI Business OS Rewiring Phase 3 — AI Generate(Website Builder) 완료 후 고객별 독립 GitHub
 * Repository + Vercel Project를 자동 생성·연결·배포하는 오케스트레이터. 기존 AI Generate
 * Workflow(lib/aiJobs/{worker,executor}.ts)는 수정하지 않고, 그 성공 이후에만 호출된다
 * (lib/aiJobs/worker.ts의 triggerDeployment() 참고).
 *
 * 8단계 매핑:
 *  1. AI Generate 완료           → 호출자(worker.ts)의 책임, 이 함수의 전제조건
 *  2. GitHub Repository 생성     → lib/github/client.ts createRepository()
 *  3. Commit                     → lib/git/client.ts ensureRepoInitialized()/commitAll()
 *  4. Push                       → lib/git/client.ts pushToRemote()
 *  5. Vercel Project 생성        → lib/vercel/client.ts createProject()
 *  6. GitHub Repository 연결     → lib/vercel/client.ts linkGitRepository()
 *  7. Production Deploy 실행     → lib/vercel/client.ts createDeployment()
 *  8. 배포 URL을 Website 레코드에 저장 → lib/websites/registry.ts updateWebsiteDeployment()
 *
 * 각 함수를 deps 객체로 주입 가능하게 해(store 주입과 동일한 원칙) 실제 네트워크·프로세스 호출
 * 없이 단위 테스트할 수 있다.
 */

export interface DeploymentPipelineDeps {
  isGitHubConfigured: typeof isGitHubConfigured;
  isVercelConfigured: typeof isVercelConfigured;
  createRepository: typeof createRepository;
  deleteRepository: typeof deleteRepository;
  ensureRepoInitialized: typeof ensureRepoInitialized;
  commitAll: typeof commitAll;
  pushToRemote: typeof pushToRemote;
  createProject: typeof createProject;
  linkGitRepository: typeof linkGitRepository;
  createDeployment: typeof createDeployment;
  deleteProject: typeof deleteProject;
}

const DEFAULT_DEPS: DeploymentPipelineDeps = {
  isGitHubConfigured,
  isVercelConfigured,
  createRepository,
  deleteRepository,
  ensureRepoInitialized,
  commitAll,
  pushToRemote,
  createProject,
  linkGitRepository,
  createDeployment,
  deleteProject,
};

const NON_ALNUM_PATTERN = new RegExp("[^a-zA-Z0-9\\s-]", "g");
const WHITESPACE_PATTERN = new RegExp("\\s+", "g");
const REPEATED_DASH_PATTERN = new RegExp("-+", "g");

/**
 * GitHub repo 이름 제약(영문/숫자/`-`/`_`/`.`)에 맞춘다 — 한글 등 비ASCII 문자는 전부 제거된다
 * (siteType처럼 이미 영문인 값 위주로 쓰이는 것을 전제, 한글만 있는 이름은 "site"로 폴백됨).
 */
function slugify(name: string): string {
  const ascii = name
    .normalize("NFKD")
    .replace(NON_ALNUM_PATTERN, "")
    .trim()
    .toLowerCase()
    .replace(WHITESPACE_PATTERN, "-")
    .replace(REPEATED_DASH_PATTERN, "-");

  return ascii || "site";
}

function pushLog(logs: DeploymentStepLog[], step: string, success: boolean, message: string): void {
  logs.push({ step, success, message, at: new Date().toISOString() });
}

export async function runDeploymentPipeline(
  input: DeploymentPipelineInput,
  deps: DeploymentPipelineDeps = DEFAULT_DEPS,
  store?: CollectionStore
): Promise<DeploymentPipelineResult> {
  const logs: DeploymentStepLog[] = [];

  // 전제조건 — GITHUB_TOKEN/VERCEL_TOKEN이 없으면 실제 리소스를 만들 수 없다. 진짜처럼 보이는
  // 가짜 URL을 지어내지 않고(lib/design/figma-generator.ts의 "simulated" 폴백과 다른 선택 —
  // 저장소/배포 URL은 클릭하면 실제로 열리는 리소스를 가리켜야 하므로), 설정되지 않았다는
  // 사실을 그대로 기록하고 종료한다.
  if (!deps.isGitHubConfigured() || !deps.isVercelConfigured()) {
    const message = "GITHUB_TOKEN 또는 VERCEL_TOKEN이 설정되지 않아 배포 파이프라인을 건너뜁니다.";
    pushLog(logs, "precondition", false, message);

    await recordAuditEvent({
      action: "deployment.pipeline.failed",
      actor: null,
      success: false,
      detail: message,
      metadata: { websiteId: input.websiteId },
    });
    await updateWebsiteDeployment(input.websiteId, { deploymentStatus: "NotConfigured", deploymentError: message }, store);

    return { success: false, status: "NotConfigured", logs, repository: null, deployment: null, error: message, rolledBack: false };
  }

  const repoName = `${slugify(input.repoBaseName)}-${input.websiteId.slice(-8)}`;

  let repository: Awaited<ReturnType<typeof createRepository>> | null = null;
  let vercelProject: Awaited<ReturnType<typeof createProject>> | null = null;

  try {
    // 2. GitHub Repository 생성
    repository = await deps.createRepository({
      name: repoName,
      private: true,
      description: `Auto-generated by AI Business OS (website ${input.websiteId})`,
    });
    pushLog(logs, "github.create_repo", true, `저장소 생성됨: ${repository.fullName}`);
    await recordAuditEvent({
      action: "deployment.github.create_repo",
      actor: null,
      success: true,
      detail: repository.fullName,
      metadata: { websiteId: input.websiteId },
    });

    // 3. Commit
    const initResult = await deps.ensureRepoInitialized(input.outDir);
    if (!initResult.success) throw new Error(`git init 실패: ${initResult.error}`);

    const commitResult = await deps.commitAll(input.outDir, "Initial deployment via AI Business OS");
    if (!commitResult.success) throw new Error(`git commit 실패: ${commitResult.error}`);
    pushLog(logs, "git.commit", true, "커밋 완료");

    // 4. Push
    const pushResult = await deps.pushToRemote(
      input.outDir,
      repository.htmlUrl,
      process.env.GITHUB_TOKEN ?? "",
      repository.defaultBranch
    );
    if (!pushResult.success) throw new Error(`git push 실패: ${pushResult.error}`);
    pushLog(logs, "git.push", true, "푸시 완료");
    await recordAuditEvent({
      action: "deployment.git.commit_push",
      actor: null,
      success: true,
      detail: repository.fullName,
      metadata: { websiteId: input.websiteId },
    });

    // 5. Vercel Project 생성
    vercelProject = await deps.createProject(repoName);
    pushLog(logs, "vercel.create_project", true, `Vercel 프로젝트 생성됨: ${vercelProject.name}`);
    await recordAuditEvent({
      action: "deployment.vercel.create_project",
      actor: null,
      success: true,
      detail: vercelProject.name,
      metadata: { websiteId: input.websiteId, projectId: vercelProject.id },
    });

    // 6. GitHub Repository 연결
    const linkResult = await deps.linkGitRepository(vercelProject.id, repository.fullName);
    if (!linkResult.success) throw new Error(`Vercel-GitHub 연결 실패: ${linkResult.error}`);
    pushLog(logs, "vercel.link_repo", true, "GitHub 저장소 연결 완료");
    await recordAuditEvent({
      action: "deployment.vercel.link_repo",
      actor: null,
      success: true,
      detail: repository.fullName,
      metadata: { websiteId: input.websiteId, projectId: vercelProject.id },
    });

    // 7. Production Deploy 실행
    const deployment = await deps.createDeployment({
      name: repoName,
      projectId: vercelProject.id,
      gitBranch: repository.defaultBranch,
    });
    pushLog(logs, "vercel.deploy", true, `배포 완료: ${deployment.url}`);
    await recordAuditEvent({
      action: "deployment.vercel.deploy",
      actor: null,
      success: true,
      detail: deployment.url,
      metadata: { websiteId: input.websiteId, deploymentId: deployment.id },
    });

    // 8. 배포 URL을 Website 레코드에 저장
    await updateWebsiteDeployment(
      input.websiteId,
      {
        repository: {
          owner: repository.owner,
          name: repository.name,
          fullName: repository.fullName,
          htmlUrl: repository.htmlUrl,
          cloneUrl: repository.cloneUrl,
        },
        deployment: {
          vercelProjectId: vercelProject.id,
          vercelProjectName: vercelProject.name,
          deploymentId: deployment.id,
          url: deployment.url,
        },
        deploymentStatus: "Success",
        deploymentError: null,
      },
      store
    );

    await recordAuditEvent({
      action: "deployment.pipeline.success",
      actor: null,
      success: true,
      detail: deployment.url,
      metadata: { websiteId: input.websiteId },
    });

    return { success: true, status: "Success", logs, repository, deployment, rolledBack: false };
  } catch (error) {
    const message = error instanceof Error ? error.message : "알 수 없는 오류";
    pushLog(logs, "pipeline.failed", false, message);
    await recordAuditEvent({
      action: "deployment.pipeline.failed",
      actor: null,
      success: false,
      detail: message,
      metadata: { websiteId: input.websiteId },
    });

    // 롤백 — 이미 생성된 외부 리소스를 역순으로 정리한다. 로컬 git commit/push는 되돌리지 않는다
    // (원격 저장소 자체를 지우므로 별도로 revert할 대상이 없음).
    let rolledBack = true;

    if (vercelProject) {
      const rollbackResult = await deps.deleteProject(vercelProject.id);
      pushLog(logs, "rollback.vercel_project", rollbackResult.success, rollbackResult.error ?? "Vercel 프로젝트 롤백 완료");
      if (!rollbackResult.success) rolledBack = false;
    }

    if (repository) {
      const rollbackResult = await deps.deleteRepository(repository.fullName);
      pushLog(logs, "rollback.github_repo", rollbackResult.success, rollbackResult.error ?? "GitHub 저장소 롤백 완료");
      if (!rollbackResult.success) rolledBack = false;
    }

    await recordAuditEvent({
      action: "deployment.pipeline.rollback",
      actor: null,
      success: rolledBack,
      detail: rolledBack ? "롤백 완료" : "롤백 일부 실패 — 수동 확인 필요",
      metadata: { websiteId: input.websiteId, repository: repository?.fullName, vercelProjectId: vercelProject?.id },
    });

    await updateWebsiteDeployment(input.websiteId, { deploymentStatus: "Failed", deploymentError: message }, store);

    return { success: false, status: "Failed", logs, repository, deployment: null, error: message, rolledBack };
  }
}
