import path from "path";
import { getMemory } from "../memory/manager.js";
import type { MemoryRecord } from "../memory/types.js";
import { generateWebsiteProject } from "../generators/website.js";
import { executeTool } from "../tools/manager.js";
import { generateSiteContent, type SiteContent } from "./content.js";
import { PALETTES, isWebsiteType, siteTypeLabel, type WebsiteInputs, type WebsiteType } from "./types.js";
import { WEBSITE_PIPELINE_AGENTS } from "./agents.js";
import { WEBSITE_WORKFLOW_NAME } from "./workflow.js";

export type { WebsiteInputs } from "./types.js";
export { WEBSITE_TYPES } from "./types.js";

const LANGUAGE_CODES: Record<string, string> = {
  english: "en",
  en: "en",
  korean: "ko",
  ko: "ko",
  "한국어": "ko",
  japanese: "ja",
  ja: "ja",
  spanish: "es",
  es: "es"
};

function languageCode(language: string): string {
  const normalized = language.trim().toLowerCase();
  return LANGUAGE_CODES[normalized] ?? (normalized.slice(0, 2) || "en");
}

export function slugify(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-+|-+$)/g, "") || "website";
}

/** `--site-type`가 없거나 목록에 없으면 범용 타입("website")으로 폴백한다. */
export function resolveSiteType(value: string | undefined): WebsiteType {
  if (value && isWebsiteType(value.trim().toLowerCase())) {
    return value.trim().toLowerCase() as WebsiteType;
  }
  return "website";
}

function firstLetter(value: string): string {
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed[0].toUpperCase() : "W";
}

function stepMessage(memory: MemoryRecord, agent: string): string {
  const step = memory.steps[agent];
  const message = step?.output?.message;
  return typeof message === "string" ? message : "";
}

/**
 * Website Builder Workflow(8단계 Planning Agent)의 결과를 사람이 읽는 문서로 남긴다.
 * 실제 페이지 콘텐츠는 이 문서가 아니라 Content Engine(content.ts, Provider Layer 직접
 * 호출)이 만든다 — 이 문서는 파이프라인이 무엇을 계획했는지 보여주는 부산물이다.
 */
function buildPlanningDocument(inputs: WebsiteInputs, memory: MemoryRecord): string {
  const output: string[] = [
    "# Planning Artifacts",
    "",
    "Generated by the AI Business OS Website Builder pipeline (`ai website create`).",
    "",
    "## Inputs",
    "",
    `- Project Name: ${inputs.projectName}`,
    `- Site Type: ${siteTypeLabel(inputs.siteType)} (${inputs.siteType})`,
    `- Business Type: ${inputs.businessType}`,
    `- Target Audience: ${inputs.targetAudience}`,
    `- Brand: ${inputs.brand}`,
    `- Language: ${inputs.language}`,
    "",
    "## Pipeline Output",
    ""
  ];

  for (const agent of WEBSITE_PIPELINE_AGENTS) {
    const step = memory.steps[agent];
    output.push(`### ${agent}`, "");
    output.push(step ? stepMessage(memory, agent) || "(no output)" : "(not run)");
    output.push("");
  }

  return output.join("\n");
}

interface SiteConfigData {
  projectName: string;
  projectSlug: string;
  siteType: WebsiteType;
  siteTypeLabel: string;
  businessType: string;
  targetAudience: string;
  brand: string;
  language: string;
  languageCode: string;
  url: string;
  seoTitle: string;
  seoDescription: string;
  contactEmail: string;
}

export interface ScaffoldResult {
  targetDir: string;
  files: string[];
  content: SiteContent;
  contentSimulated: boolean;
}

/**
 * Website Builder Workflow의 결과(Memory)를 문서로 남기고, Content Engine + Generator를
 * 재사용해 실제 Next.js 프로젝트를 생성한다.
 * - 콘텐츠: Content Engine(generateSiteContent, Provider Layer 재사용)
 * - 정적 스캐폴딩: Generator(generateWebsiteProject → generateFromTemplate) 단일 호출.
 *   모든 동적 값(색상 팔레트·siteConfig·content)은 `{{var}}` 치환 변수로만 전달되며,
 *   파일을 개별적으로 다시 쓰는 별도 로직은 두지 않는다(요구사항 9 — 중복 실행 로직 없음).
 * - PLANNING.md만 Tool System(filesystem)으로 별도 기록한다(Memory 기반 부산물이라
 *   템플릿 변수로 표현하기보다 그대로 기록하는 것이 더 정확하다).
 */
export async function scaffoldWebsiteProject(
  cwd: string,
  targetDir: string,
  inputs: WebsiteInputs,
  providerId?: string
): Promise<ScaffoldResult> {
  const memory = await getMemory(cwd, WEBSITE_WORKFLOW_NAME);

  const { content, simulated } = await generateSiteContent(cwd, inputs, providerId);
  const palette = PALETTES[inputs.siteType];

  const siteConfig: SiteConfigData = {
    projectName: inputs.projectName,
    projectSlug: inputs.projectSlug,
    siteType: inputs.siteType,
    siteTypeLabel: siteTypeLabel(inputs.siteType),
    businessType: inputs.businessType,
    targetAudience: inputs.targetAudience,
    brand: inputs.brand,
    language: inputs.language,
    languageCode: languageCode(inputs.language),
    url: `https://${inputs.projectSlug}.example.com`,
    seoTitle: content.seo.title,
    seoDescription: content.seo.description,
    contactEmail: content.contact.email
  };

  const result = await generateWebsiteProject({
    targetDir,
    variables: {
      projectName: inputs.projectName,
      projectSlug: inputs.projectSlug,
      businessType: inputs.businessType,
      targetAudience: inputs.targetAudience,
      brand: inputs.brand,
      language: inputs.language,
      languageCode: languageCode(inputs.language),
      siteType: inputs.siteType,
      siteTypeLabel: siteTypeLabel(inputs.siteType),
      seoTitle: content.seo.title,
      seoDescription: content.seo.description,
      siteUrl: siteConfig.url,
      initial: firstLetter(inputs.brand || inputs.projectName),
      colorPrimary: palette.primary,
      colorPrimaryDark: palette.primaryDark,
      colorSecondary: palette.secondary,
      colorAccent: palette.accent,
      colorBackground: palette.background,
      colorForeground: palette.foreground,
      colorMuted: palette.muted,
      colorBorder: palette.border,
      colorSuccess: palette.success,
      colorWarning: palette.warning,
      colorDanger: palette.danger,
      siteConfigJson: JSON.stringify(siteConfig, null, 2),
      contentJson: JSON.stringify(content, null, 2)
    }
  });

  const planningDocument = buildPlanningDocument(inputs, memory);

  // Tool System 재사용 — Memory 기반 동적 문서는 filesystem 도구로 기록한다.
  await executeTool("filesystem", {
    action: "write",
    path: "PLANNING.md",
    content: planningDocument,
    cwd: targetDir
  });

  return {
    targetDir,
    files: [...result.files, path.join(targetDir, "PLANNING.md")],
    content,
    contentSimulated: simulated
  };
}
