import path from "path";
import { getMemory } from "../memory/manager.js";
import type { MemoryRecord } from "../memory/types.js";
import { generateWebsiteProject } from "../generators/website.js";
import { executeTool } from "../tools/manager.js";
import { WEBSITE_PIPELINE_AGENTS } from "./agents.js";
import { WEBSITE_WORKFLOW_NAME } from "./workflow.js";

export interface WebsiteInputs {
  projectName: string;
  businessType: string;
  targetAudience: string;
  brand: string;
  language: string;
}

const LANGUAGE_CODES: Record<string, string> = {
  english: "en",
  en: "en",
  korean: "ko",
  ko: "ko",
  "한국어": "ko",
  japanese: "ja",
  ja: "ja",
  spanish: "es",
  es: "es"
};

function languageCode(language: string): string {
  const normalized = language.trim().toLowerCase();
  return LANGUAGE_CODES[normalized] ?? (normalized.slice(0, 2) || "en");
}

export function slugify(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-+|-+$)/g, "") || "website";
}

function stepMessage(memory: MemoryRecord, agent: string): string {
  const step = memory.steps[agent];
  const message = step?.output?.message;
  return typeof message === "string" ? message : "";
}

function isSimulated(text: string): boolean {
  return text.startsWith("[simulated]");
}

function lines(text: string): string[] {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

/**
 * Website Builder Workflow의 결과(Memory)를 읽어 실제 Next.js 프로젝트를 생성한다.
 * - 실제 LLM(provider)로 실행되어 시뮬레이션이 아닌 콘텐츠가 있으면 그것을 사용하고,
 *   시뮬레이션된 경우(provider 미설정)에는 사용자가 입력한 구조적 정보(프로젝트명/업종/
 *   타겟 고객)로 합리적인 기본값을 구성한다 — Agent Runtime의 "시뮬레이션 폴백"과
 *   동일한 정신이다.
 * - 정적 프로젝트 스캐폴딩은 Generator(generateWebsiteProject)를 재사용하고,
 *   Memory 기반의 동적 PLANNING.md는 Tool System(filesystem)으로 기록한다.
 */
export async function scaffoldWebsiteProject(
  cwd: string,
  targetDir: string,
  inputs: WebsiteInputs
): Promise<{ targetDir: string; files: string[] }> {
  const memory = await getMemory(cwd, WEBSITE_WORKFLOW_NAME);

  const pageCopy = stepMessage(memory, "page-generator");
  const seoText = stepMessage(memory, "seo-generator");

  const pageCopyLines = lines(pageCopy);
  const seoLines = lines(seoText);

  const heroHeadline =
    !isSimulated(pageCopy) && pageCopyLines[0] ? pageCopyLines[0] : `Welcome to ${inputs.projectName}`;
  const heroSubheadline =
    !isSimulated(pageCopy) && pageCopyLines[1]
      ? pageCopyLines[1]
      : `${inputs.businessType} for ${inputs.targetAudience}, by ${inputs.brand}.`;
  const seoTitle =
    !isSimulated(seoText) && seoLines[0] ? seoLines[0] : `${inputs.projectName} | ${inputs.businessType}`;
  const seoDescription =
    !isSimulated(seoText) && seoLines[1]
      ? seoLines[1]
      : `${inputs.projectName} is a ${inputs.businessType} serving ${inputs.targetAudience}.`;

  const result = await generateWebsiteProject({
    targetDir,
    variables: {
      projectName: inputs.projectName,
      projectSlug: slugify(inputs.projectName),
      businessType: inputs.businessType,
      targetAudience: inputs.targetAudience,
      brand: inputs.brand,
      language: inputs.language,
      languageCode: languageCode(inputs.language),
      heroHeadline,
      heroSubheadline,
      seoTitle,
      seoDescription
    }
  });

  const planningDocument = buildPlanningDocument(inputs, memory);

  // Tool System 재사용 — Memory 기반 동적 문서는 filesystem 도구로 기록한다.
  await executeTool("filesystem", {
    action: "write",
    path: "PLANNING.md",
    content: planningDocument,
    cwd: targetDir
  });

  return { targetDir, files: [...result.files, path.join(targetDir, "PLANNING.md")] };
}

function buildPlanningDocument(inputs: WebsiteInputs, memory: MemoryRecord): string {
  const output: string[] = [
    "# Planning Artifacts",
    "",
    "Generated by the AI Business OS Website Builder pipeline (`ai website create`).",
    "",
    "## Inputs",
    "",
    `- Project Name: ${inputs.projectName}`,
    `- Business Type: ${inputs.businessType}`,
    `- Target Audience: ${inputs.targetAudience}`,
    `- Brand: ${inputs.brand}`,
    `- Language: ${inputs.language}`,
    "",
    "## Pipeline Output",
    ""
  ];

  for (const agent of WEBSITE_PIPELINE_AGENTS) {
    const step = memory.steps[agent];
    output.push(`### ${agent}`, "");
    output.push(step ? stepMessage(memory, agent) || "(no output)" : "(not run)");
    output.push("");
  }

  return output.join("\n");
}
